# HW 14 - Dictionaries

###  Exercise 1 - Swap keys and values
Swap keys and values in a given dictionary

In [1]:
planet_radius = {
    'Mercury': 4879,
    'Venus': 12104,
    'Earth': 12756,
    'Mars': 6792,
    'Jupiter': 142984,
    'Saturn': 120536,
    'Uranus': 51118,
    'Neptune': 49528,
    'Pluto': 2370}

swapped = {value:key for key, value in planet_radius.items()}
print(swapped)

{4879: 'Mercury', 12104: 'Venus', 12756: 'Earth', 6792: 'Mars', 142984: 'Jupiter', 120536: 'Saturn', 51118: 'Uranus', 49528: 'Neptune', 2370: 'Pluto'}


### Exercise 2 - Create a dictionary
Create a dictionary for the following lists in two different ways: using "zip" function and using comprehension.

In [5]:
exo_planet = "Kepler-10b HD_209458b Kepler-22b Kepler-186f TRAPPIST-1e HD-189733b Kepler-442b WASP-12b Proxima_Centauri_b"
orbital_periods = [0.84, 3.52, 289.9, 129.9, 6.10,2.22, 112.3, 1.09, 11.2]   # Orbital period in Earth days

planet_list = exo_planet.split(" ")

# zip method
dictionary_zip_method = dict(zip(planet_list, orbital_periods))

# comprehension method
dictionary_comprehension_method = {planet_list[i]:orbital_periods[i] for i in range(len(orbital_periods))}

### Exercise 3 - Restore an text
Restore an English text which was accidentally written with the keyboard in Hebrew mode.

In [8]:
heb2eng = {
    "א": "t",
    "ב": "c",
    "ג": "d",
    "ד": "s",
    "ה": "v",
    "ו": "u",
    "ז": "z",
    "ח": "j",
    "ט": "y",
    "י": "h",
    "כ": "f",
    "ל": "k",
    "מ": "n",
    "נ": "b",
    "ס": "x",
    "ע": "g",
    "פ": "p",
    "צ": "m",
    "ק": "e",
    "ר": "r",
    "ש": "a",
    "ת": ",",
    "ך": "l",
    " ": " ",
    "ם": "o",
    "ן": "i",
    "'": "w",
    "/": "q",
}

text = "ן פרקכקר חשהש אם פטאיםמ"

translated = ""

for char in text.lower():
    translated += heb2eng[char]

print(translated)

i prefer java to python


### Exercise 4 - Bigger than Earth
Use comprehenstion to print planets (name and radius) that are  bigger than earth.

In [10]:
planet_radius = {
    'Mercury': 4879,
    'Venus': 12104,
    'Earth': 12756,
    'Mars': 6792,
    'Jupiter': 142984,
    'Saturn': 120536,
    'Uranus': 51118,
    'Neptune': 49528,
    'Pluto': 2370
}

planets_bigger_than_earth = [print(key, " : ", value) if value > planet_radius['Earth'] else print("", end="") for key, value in planet_radius.items()]

Jupiter  :  142984
Saturn  :  120536
Uranus  :  51118
Neptune  :  49528


### Exercise 5 - Combining astronomical data 
Create a function that combines astronomical object data from multiple catalogs or observations. Each catalog captures different properties of celestial objects. \
Use the ** operator to merge these properties, with a prioritization list that determines which catalog's value to keep when conflicts occur.

In [4]:
optical_data = {"name": "M31", "ra": "00h42m44.3s", "dec": "+41°16′9″", "magnitude": 3.4, "type": "Spiral Galaxy"}
radio_data = {"name": "Andromeda", "flux_density_Jy": 15.3, "redshift": 0.000804, "type": "Galaxy"}
derived_data = {"distance_Mly": 2.5, "stellar_mass_solar": 1e12, "diameter_kly": 220}
priority_order = ["radio_data", "optical_data", "derived_data"]  # Which catalog to prioritize for conflicts


ordered_dictionaries = {"radio_data":radio_data, "optical_data":optical_data, "derived_data":derived_data}

# combining when radio data is the most important, in ascending order
combined_asc = {}
for curr_data_name in priority_order:
    curr_data = ordered_dictionaries[curr_data_name]
    for item in curr_data.keys():
        if not item in combined_asc:
            combined_asc[item] = curr_data[item]

print(combined_asc)


# combining when derived data is the most important, in descending order
combined_des = {}
for curr_data_name in reversed(priority_order):
    curr_data = ordered_dictionaries[curr_data_name]
    for item in curr_data.keys():
        if not item in combined_des:
            combined_des[item] = curr_data[item]

print(combined_des)

{'name': 'Andromeda', 'flux_density_Jy': 15.3, 'redshift': 0.000804, 'type': 'Galaxy', 'ra': '00h42m44.3s', 'dec': '+41°16′9″', 'magnitude': 3.4, 'distance_Mly': 2.5, 'stellar_mass_solar': 1000000000000.0, 'diameter_kly': 220}
{'distance_Mly': 2.5, 'stellar_mass_solar': 1000000000000.0, 'diameter_kly': 220, 'name': 'M31', 'ra': '00h42m44.3s', 'dec': '+41°16′9″', 'magnitude': 3.4, 'type': 'Spiral Galaxy', 'flux_density_Jy': 15.3, 'redshift': 0.000804}


### Exercise 6 - Element Properties Dictionary

1. Create a dictionary called `elements` where each key is an element name and each value is a nested dictionary containing "atomic_number", "atomic_weight", and "state".
2. Write code to print all elements that are gases at room temperature.
3. Find and print the element with the highest atomic weight.
4. Add a new property "discovered_year" to each element with the following values: Hydrogen: 1766, Oxygen: 1774, Iron: Ancient times (5000 BCE), Mercury: Ancient times (2000 BCE), Helium: 1895.



In [23]:
element_names = ["Hydrogen", "Oxygen", "Iron", "Mercury", "Helium"]

# Properties (in the same order as names)
atomic_numbers = [1, 8, 26, 80, 2]
atomic_weights = [1.008, 16.00, 55.85, 200.59, 4.003]
states = ["gas", "gas", "solid", "liquid", "gas"]

elements = {element_names[i]:{"atomic_number":atomic_numbers[i], "atomic_weight":atomic_weights[i], "state":states[i]} for i in range(len(element_names))}
print(elements)


print("\n")
heaviest = ""
for element in elements.keys():
    if elements[element]["state"] == "gas":
        print(element)
    if heaviest == "" or elements[element]["atomic_weight"] > elements[heaviest]["atomic_weight"]:
        heaviest = element
print("\n")
print(heaviest)

discovered_years = ["1766", "1774", "5000 BCE", "2000 BCE", "1895"]
for i in range(len(discovered_years)):
    elements[list(elements)[i]]["discovered_year"] = discovered_years[i]

print(elements)

{'Hydrogen': {'atomic_number': 1, 'atomic_weight': 1.008, 'state': 'gas'}, 'Oxygen': {'atomic_number': 8, 'atomic_weight': 16.0, 'state': 'gas'}, 'Iron': {'atomic_number': 26, 'atomic_weight': 55.85, 'state': 'solid'}, 'Mercury': {'atomic_number': 80, 'atomic_weight': 200.59, 'state': 'liquid'}, 'Helium': {'atomic_number': 2, 'atomic_weight': 4.003, 'state': 'gas'}}


Hydrogen
Oxygen
Helium


Mercury
{'Hydrogen': {'atomic_number': 1, 'atomic_weight': 1.008, 'state': 'gas', 'discovered_year': '1766'}, 'Oxygen': {'atomic_number': 8, 'atomic_weight': 16.0, 'state': 'gas', 'discovered_year': '1774'}, 'Iron': {'atomic_number': 26, 'atomic_weight': 55.85, 'state': 'solid', 'discovered_year': '5000 BCE'}, 'Mercury': {'atomic_number': 80, 'atomic_weight': 200.59, 'state': 'liquid', 'discovered_year': '2000 BCE'}, 'Helium': {'atomic_number': 2, 'atomic_weight': 4.003, 'state': 'gas', 'discovered_year': '1895'}}


#### Output:

1. 
{'Hydrogen': {'atomic_numbers': 1, 'atomic_weights': 1.008, 'states': 'gas'}, \
 'Oxygen': {'atomic_numbers': 8, 'atomic_weights': 16.0, 'states': 'gas'}, \
 'Iron': {'atomic_numbers': 26, 'atomic_weights': 55.85, 'states': 'solid'}, \
 'Mercury': {'atomic_numbers': 80, 'atomic_weights': 200.59, 'states': 'liquid'}, \
 'Helium': {'atomic_numbers': 2, 'atomic_weights': 4.003, 'states': 'gas'}}

2. 
Hydrogen
Oxygen
Helium

3. 
Mercury
  
4. 
{'Hydrogen': {'atomic_numbers': 1, 'atomic_weights': 1.008, 'states': 'gas', 'discovered_year': '1766'},
 'Oxygen': {'atomic_numbers': 8, 'atomic_weights': 16.0, 'states': 'gas', 'discovered_year': '1774'},
 'Iron': {'atomic_numbers': 26, 'atomic_weights': 55.85, 'states': 'solid', 'discovered_year': '5000 BCE'},
 'Mercury': {'atomic_numbers': 80, 'atomic_weights': 200.59, 'states': 'liquid', 'discovered_year': '2000 BCE'},
 'Helium': {'atomic_numbers': 2, 'atomic_weights': 4.003, 'states': 'gas', 'discovered_year': '1895'}}


### Exercise 7: Astronomical Database

1. Create a nested dictionary called `planets` where each key is a planet name and each value is a dictionary containing "distance_from_sun", "moons", "orbital_period", and "composition" (which is itself a dictionary).
2. Create a function that takes a number as input and returns all planets with more moons than that number.
3. Write a function to identify planets with similar composition (at least one component with >30% difference in components percentage).

In [9]:
def composition_array_to_dictionary(inpt):
    out = {}
    for i in range(0, len(inpt), 2):
        out[inpt[i]] = inpt[i+1]
    
    return out


planet_names = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn"]

# Planet data (in the same order as names)
distances = [0.39, 0.72, 1.00, 1.52, 5.20, 9.58]  # in AU
moon_counts = [0, 0, 1, 2, 79, 82]
orbital_periods = [0.24, 0.62, 1.00, 1.88, 11.86, 29.46]  # in Earth years

# Composition data (percentages of main components)
mercury_comp = ["iron", 70, "silicate", 30]
venus_comp = ["carbon_dioxide", 96, "nitrogen", 3, "sulfur_dioxide", 1]
earth_comp = ["nitrogen", 78, "oxygen", 21, "other_gases", 1]
mars_comp = ["iron_oxide", 70, "silicate", 30]
jupiter_comp = ["hydrogen", 90, "helium", 10]
saturn_comp = ["hydrogen", 96, "helium", 3, "other", 1]

planet_compositions = [mercury_comp, venus_comp, earth_comp, mars_comp, jupiter_comp, saturn_comp]

planets = {
    planet_names[i]:
    {
        "distance_from_sun":distances[i], 
        "moons":moon_counts[i], 
        "orbital_period":orbital_periods[i], 
        "composition":composition_array_to_dictionary(planet_compositions[i])
    }
    for i in range(len(planet_names))
    }

def get_planets_with_more_moons_than(amount):
    global planet_names, planets
    relevant_planets = []
    for planet in planet_names:
        if planets[planet]["moons"] > amount:
            relevant_planets.append(planet)
    return relevant_planets

print(get_planets_with_more_moons_than(1))


def get_all_similar_composition_planets(tolerance=30.0):

    # im assuming this means that the difference between any two identical components must be no more than 30%
    def is_two_planets_similar_comp(comp1, comp2):
        for item in comp1:
            if not item in comp2:
                comp2[item] = 0
        
        for item in comp2:
            if not item in comp1:
                comp1[item] = 0
        

        for item in comp1:
            if abs(comp1[item] - comp2[item]) > tolerance:
                return False
        return True
    
    # contains tuples of similar planet names
    similar = []
    for i in range(len(planet_names)):
        for j in range(i+1, len(planet_names)):
            if is_two_planets_similar_comp(planets[planet_names[i]]["composition"], planets[planet_names[j]]["composition"]):
                similar.append((planet_names[i], planet_names[j]))
    
    return similar

print(get_all_similar_composition_planets())

['Mars', 'Jupiter', 'Saturn']
[('Jupiter', 'Saturn')]
